demo/SchedulerDemo/urls.py
from django.urls import path

from SchedulerDemo.views import CouponView, CouponDetailView
from .views import TasksHomeFormView, JobTemplateView

urlpatterns = [
    path('', TasksHomeFormView.as_view(), name='home'),
    # path('long/', LongTaskCreateView.as_view(), name='long_tasks'),
    path('job/<job>/', JobTemplateView.as_view(), name='view_job'),
    path('coupon/', CouponView.as_view(), name='coupon_detail'),
    path('coupon/<coupon_id>/', CouponDetailView.as_view(), name='a_coupon_detail')

]

demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls')),
    path('scheduler/', include('SchedulerDemo.urls')),
]

demo/SchedulerDemo/models.py
import datetime
from django.db import models
from django.utils.translation import ugettext_lazy as _

GET = "get"
SAVE = "save"
COUPON_HASH_TYPES = (
    (GET, _("GET")),
    (SAVE, _("SAVE"))
)


class Coupon(models.Model):
    name = models.CharField(max_length=100, default="A coupon", blank = False)
    created_on = models.DateTimeField(_("Created On"),blank=False, default = datetime.datetime.now())
    type = models.CharField(_("Type"), max_length=5, choices=COUPON_HASH_TYPES)

class Task(models.Model):
    # A model to save information about an asynchronous task
    created_on = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    job_id = models.CharField(max_length=128)
    result = models.CharField(max_length=128, blank=True, null=True)


class ScheduledTask(models.Model):
    # A model to save information about a scheduled task
    created_on = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    # A scheduled task has a common job id for all its occurences
    job_id = models.CharField(max_length=128)


class ScheduledTaskInstance(models.Model):
    # A model to save information about instances of a scheduled task
    scheduled_task = models.ForeignKey('ScheduledTask', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    result = models.CharField(max_length=128, blank=True, null=True)

demo/SchedulerDemo/forms.py
from django import forms


class TaskForm(forms.Form):
    """ A simple form to read a url from the user in order to find out its length
    and either run it asynchronously or schedule it schedule_times times,
    every schedule_interval seconds.
    """
    url = forms.CharField(label='URL', max_length=128, help_text='Enter a url (starting with http/https) to start a job that will download it and count its words' )
    schedule_times = forms.IntegerField(required=False, help_text='How many times to run this job. Leave empty or 0 to run it only once.')
    schedule_interval = forms.IntegerField(required=False, help_text='How much time (in seconds) between runs of the job. Leave empty to run it only once.')

    def clean(self):
        data = super(TaskForm, self).clean()
        schedule_times = data.get('schedule_times')
        schedule_interval = data.get('schedule_interval')

        if schedule_times and not schedule_interval or not schedule_times and schedule_interval:
            msg = 'Please fill both schedule_times and schedule_interval to schedule a job or leave them both empty'
            self.add_error('schedule_times', msg)
            self.add_error('schedule_interval', msg)

demo/SchedulerDemo/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.utils import timezone
from .forms import TaskForm
from .tasks import get_url_words, scheduled_get_url_words, get_title_change, change_coupon_type
from .models import Task, ScheduledTask, Coupon
from rq.job import Job
import django_rq
import datetime


class TasksHomeFormView(FormView):
    """
    A class that displays a form to read a url to read its contents and if the job
    is to be scheduled or not and information about all the tasks and scheduled tasks.

    When the form is submitted, the task will be either scheduled based on the
    parameters of the form or will be just executed asynchronously immediately.
    """
    form_class = TaskForm
    template_name = "tasks_home.html"
    success_url = '/scheduler/'

    def form_valid(self, form):
        url = form.cleaned_data['url']
        schedule_times = form.cleaned_data.get('schedule_times')
        schedule_interval = form.cleaned_data.get('schedule_interval')
        timenow = datetime.datetime.now()

        if schedule_times and schedule_interval:
            # Schedule the job with the form parameters
            scheduler = django_rq.get_scheduler('default')
            job = scheduler.schedule(
                scheduled_time=timenow+ datetime.timedelta(seconds=20),
                func=scheduled_get_url_words,
                args=[url],
                interval=schedule_interval,
                repeat=schedule_times,
            )
        else:
            # Just execute the job asynchronously
            scheduler = django_rq.get_scheduler('default')
            # job = scheduler.enqueue_at(time+datetime.timedelta(seconds=10), get_url_words, url)
            job = scheduler.enqueue_at(timenow+datetime.timedelta(seconds=20), get_title_change, url)

        return super(TasksHomeFormView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(TasksHomeFormView, self).get_context_data(**kwargs)
        ctx['tasks'] = Task.objects.all().order_by('-created_on')
        ctx['scheduled_tasks'] = ScheduledTask.objects.all().order_by('-created_on')
        return ctx


class JobTemplateView(TemplateView):
    """
    A simple template view that gets a job id as a kwarg parameter
    and tries to fetch that job from RQ. It will then print all attributes
    of that object using __dict__.
    """
    template_name = "job.html"

    def get_context_data(self, **kwargs):
        ctx = super(JobTemplateView, self).get_context_data(**kwargs)
        redis_conn = django_rq.get_connection('default')
        try:
            job = Job.fetch(self.kwargs['job'], connection=redis_conn)
            job = job.__dict__
        except:
            job = None

        ctx['job'] = job
        return ctx


class CouponView(ListView):
    model = Coupon
    template_name = "coupon_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CouponView, self).get_context_data(**kwargs)
        context['coupon'] = Coupon.objects.all()
        context['time'] = timezone.now()
        return context


class CouponDetailView(DetailView):
    model = Coupon
    queryset = Coupon.objects.all()
    template_name = 'a_coupon_detail.html'
    pk_url_kwarg = 'coupon_id'

    def get_context_data(self, **kwargs):
        context = super(CouponDetailView, self).get_context_data(**kwargs)
        return context

demo/SchedulerDemo/templates/a_coupon_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>A coupon detail</title>
</head>
<body>
{{ object.name }}
{{ object.created_on }}
{{ object.type }}
<br>
<br>

</body>
</html>

demo/SchedulerDemo/templates/coupon_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coupon Detail</title>
</head>
<body>
    {%  for obj in coupon %}
        <b>{{  obj.name }}</b> was {{ obj.created_on }} and it was of type "{{ obj.type }}".  {{ time }}<br>
    {%  endfor %}
</body>
</html>

demo/SchedulerDemo/templates/job.html
  <div class="row">
        <div class="twelve columns">
            <h3>Job {{ view.kwargs.job }} attributes</h3>
        </div>
    </div>
    {% for key, val in job.items %}
        <div class="row">
            <div class="twelve columns">
                {{ key }} = {{ val }}
            </div>
        </div>
    {% endfor %}

demo/SchedulerDemo/templates/tasks_home.html
<h3>Tasks</h3>
<div class="row">
    <div class="twelve columns">
        <form method='POST'>
            {% csrf_token %}
            {{ form }}<br />
            <input type='submit' value='ok' />
        </form>
    </div>
</div>
<hr />

<h4>Tasks</h4>
<table style="width: 100%">
    <thead><tr><th>Url</th><th>Job</th><th>Result</th><th>Date</th></tr></thead>
    <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.name }}</td>
                <td><a href="{% url 'view_job' task.job_id %}" >{{ task.job_id }}</a></td>
                <td>{{ task.result }}</td><td>{{ task.created_on|date:"d/m/Y H:i" }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<h4>Scheduled Tasks</h4>
<table style="width: 100%;">
    <thead><tr><th>Url</th><th>Job</th><th>Instances</th></tr></thead>
    <tbody>
        {% for task in scheduled_tasks %}
            <tr>
                <td>{{ task.name }}</td>
                <td><a href="{% url 'view_job' task.job_id %}" >{{ task.job_id }}</a></td>
                <td>
                {% for ti in task.scheduledtaskinstance_set.all %}
                    @{{ ti.created_on|date:"d/m/Y H:i" }}, result: {{ ti.result }}<br/>
                {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

</div>